/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/merchant/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Key 목록 조회
         * @description OWNER/ADMIN만 조회할 수 있다. Secret 관련 필드(rawApiKey/secretHash)는 애초에 담기지 않는다.
         */
        get: operations["merchant-list-api-keys"];
        put?: never;
        /**
         * API Key 발급
         * @description OWNER/ADMIN만 발급할 수 있다. rawApiKey는 이 응답에서만 원문으로 보이고 DB에는 Hash만 남는다 — 다시 조회할 수 없으니 즉시 가맹점 서버에 전달해야 한다. environment는 받지 않는다(MVP는 항상 TEST).
         */
        post: operations["merchant-issue-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가맹점 콘솔 로그인
         * @description 로그인에 성공하면 세션 쿠키(Set-Cookie)를 내리고 본문에 신원 정보를 담는다. login_id는 가맹점 안에서만 유일해서 merchantCode로 어느 가맹점인지 먼저 밝힌다. 상태 변경 요청이라 CSRF 토큰(X-XSRF-TOKEN)이 필요하다 — GET /merchant/me로 먼저 XSRF-TOKEN 쿠키를 받는다.
         */
        post: operations["merchant-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 세션을 무효화한다. 본문이 없고 204를 돌려준다. 상태 변경 요청이라 CSRF 토큰이 필요하다.
         */
        post: operations["merchant-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 세션 사용자 조회(세션 복원)
         * @description 프론트가 새로고침 후 로그인 상태를 복원할 때 쓴다. 미인증이면 401을 돌려주고, 프론트는 그것을 '로그아웃 상태'로 해석한다. 이 GET은 CSRF 토큰 발급도 겸한다 — 응답에 XSRF-TOKEN 쿠키가 실린다.
         */
        get: operations["merchant-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가맹점 사용자 목록 조회
         * @description OWNER/ADMIN만 조회할 수 있다. 자신의 가맹점 명부만 나온다 — 누가 소속돼 있고 누가 아직 INVITED로 남아 있는지 확인한다. 비밀번호 해시는 담기지 않는다.
         */
        get: operations["merchant-list-merchant-users"];
        put?: never;
        /**
         * 하위 계정 발급(초대)
         * @description OWNER/ADMIN이 같은 가맹점의 ADMIN/VIEWER 하위 계정을 INVITED 상태로 만든다. merchantId는 받지 않는다 — 항상 호출자 자신의 가맹점에 만들어진다(멀티테넌시 방어). OWNER는 이 경로로 만들 수 없다. invitationToken은 이 응답에서만 원문으로 보이므로 대상자에게 즉시 전달해야 한다.
         */
        post: operations["merchant-invite-sub-account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 내역 조회(자기 가맹점)
         * @description **인증된 가맹점 사용자 전원**(VIEWER 포함)이 조회할 수 있다. 조회 범위는 세션의 가맹점으로 서버가 고정하므로 merchantId를 보낼 수 없다. 쿼리 파라미터로 좁힌다: status(PaymentStatus), from/to(생성 시각 ISO-8601 UTC), page(0부터), size. size는 서버가 최대 200으로 자르고 실제로 적용된 값을 응답의 size로 돌려준다. 정렬은 생성 시각 최신순이다. paymentAmount는 Minor Unit 정수를 **문자열로** 준다 — 토큰 금액이 JavaScript Number의 안전 정수 범위를 넘을 수 있다.
         */
        get: operations["merchant-payments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/settlement-receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 정산 채권 조회(자기 가맹점)
         * @description **인증된 가맹점 사용자 전원**(VIEWER 포함)이 조회할 수 있다. 조회 범위는 세션의 가맹점으로 서버가 고정하므로 merchantId를 보낼 수 없다. 쿼리 파라미터: status, eligibleFrom/eligibleTo(**정산 예정일 기준 날짜** YYYY-MM-DD), page, size(최대 200). **totalNetAmount는 현재 페이지가 아니라 필터 전체의 정산 예정 금액 합계**다 — "그래서 얼마를 받나"가 이 화면의 질문이다. 금액은 KRW 원 단위 정수라 모두 숫자로 준다. 응답에 가맹점 열이 없다(언제나 자기 가맹점 하나다).
         */
        get: operations["merchant-settlement-receivables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Webhook 설정 조회
         * @description 수신 URL과 **서명 비밀**을 돌려준다. 응답에 자격증명이 들어 있어 OWNER/ADMIN만 조회할 수 있다. 비밀은 저장돼 있지 않고 매번 파생되므로 몇 번이든 다시 볼 수 있다.
         */
        get: operations["merchant-get-webhook"];
        /**
         * Webhook 수신 URL 설정
         * @description `webhookUrl`을 비우거나 생략하면 설정이 해제되고, 그 뒤로는 전송 자체를 만들지 않는다.
         */
        put: operations["merchant-update-webhook-url"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/account-invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 수락(계정 활성화)
         * @description 초대받은 사람이 Token과 새 비밀번호로 계정을 INVITED → ACTIVE로 활성화한다. 인증이 필요 없고, **CSRF 토큰도 요구하지 않는다** — 자격증명이 세션 쿠키가 아니라 본문의 초대 Token 자체라 CSRF가 막으려는 상황이 성립하지 않는다(merchant-console-api.md 2절).
         */
        post: operations["merchant-accept-invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/api-keys/{merchantApiKeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * API Key 폐기
         * @description OWNER/ADMIN만 폐기할 수 있다. 폐기된 Key는 다시 활성화하지 않는다 — 새 Key를 발급한다.
         */
        delete: operations["merchant-revoke-api-key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 상세 조회(자기 가맹점)
         * @description **인증된 가맹점 사용자 전원**(VIEWER 포함)이 조회할 수 있다. 결제 한 건의 전체 맥락을 단계별로 돌려준다: 견적·체크아웃 세션·온체인 거래·환전·정산 채권·Webhook 전송 이력. **흐름이 진행돼야 생기는 부분은 null이고, 그 null 자체가 "어디까지 갔는지"를 말해준다.** 응답에 가맹점 열이 없다(언제나 자기 가맹점이다). **없는 결제와 다른 가맹점의 결제가 똑같이 404다** — 403으로 나누면 "그 결제는 존재한다"가 새어 나가 식별자를 훑어 다른 가맹점의 거래를 추정할 수 있다.
         */
        get: operations["merchant-payment-detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/webhook/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook 서명 비밀 교체
         * @description 세대를 1 올려 새 비밀을 만든다. **되돌릴 수 없고 겹치는 기간도 없다** — 가맹점 서버에 새 비밀을 반영하기 전까지 그 사이의 Webhook은 서명 불일치로 거부된다.
         */
        post: operations["merchant-rotate-webhook-secret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users/{merchantUserId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 재개
         * @description OWNER/ADMIN만 호출할 수 있다. 자기 자신은 대상이 될 수 없고, ADMIN은 OWNER를 변경할 수 없다(403). 가맹점의 마지막 활성 OWNER를 정지·종료하려 하면 409다(최소 하나의 활성 OWNER를 유지한다). 허용되지 않는 상태 전이(예: 종료된 계정 재개)도 409다.
         */
        post: operations["merchant-reactivate-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users/{merchantUserId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 역할 변경
         * @description OWNER/ADMIN만 호출할 수 있다. **OWNER로 승격할 수 없다**(400) — 최초 OWNER는 가맹점 등록에서만 생성된다. ADMIN은 OWNER의 역할을 변경할 수 없고(403), 마지막 활성 OWNER는 강등할 수 없다(409).
         */
        post: operations["merchant-change-user-role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users/{merchantUserId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 정지
         * @description OWNER/ADMIN만 호출할 수 있다. 자기 자신은 대상이 될 수 없고, ADMIN은 OWNER를 변경할 수 없다(403). 가맹점의 마지막 활성 OWNER를 정지·종료하려 하면 409다(최소 하나의 활성 OWNER를 유지한다). 허용되지 않는 상태 전이(예: 종료된 계정 재개)도 409다.
         */
        post: operations["merchant-suspend-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users/{merchantUserId}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 종료
         * @description OWNER/ADMIN만 호출할 수 있다. 자기 자신은 대상이 될 수 없고, ADMIN은 OWNER를 변경할 수 없다(403). 가맹점의 마지막 활성 OWNER를 정지·종료하려 하면 409다(최소 하나의 활성 OWNER를 유지한다). 허용되지 않는 상태 전이(예: 종료된 계정 재개)도 409다.
         */
        post: operations["merchant-terminate-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users/{merchantUserId}/invitation/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 재발송
         * @description 초대 Token은 Hash만 저장돼 원문을 다시 볼 수 없으므로, 재발송은 기존 링크를 다시 보여주는 게 아니라 **새 Token을 발급하는 것**이다 — 이전 초대 링크는 이 시점에 무효가 된다. 대상이 INVITED가 아니면 409다(이미 활성화된 계정에 다시 보낼 이유가 없다).
         */
        post: operations["merchant-resend-invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/merchant-users/{merchantUserId}/invitation/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 취소
         * @description 초대 Token을 무효화해 그 링크로는 더 이상 활성화할 수 없게 한다. **계정 자체는 INVITED로 남는다** — 계정을 없애려면 종료를 쓴다(되돌릴 수 없는 동작이 가벼운 이름 뒤에 숨지 않게 분리했다). 취소할 PENDING 초대가 없으면 409다.
         */
        post: operations["merchant-revoke-invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** IssueMerchantApiKeyResponse */
        IssueMerchantApiKeyResponse: {
            /** @description 발급 시각(UTC) */
            createdAt: string;
            /** @description 발급 환경. MVP는 TEST. */
            environment: string;
            /** @description Key 이름 */
            keyName: string;
            /** @description 전체 API Key 원문. 최초 1회만 노출된다. */
            rawApiKey: string;
            /** @description 허용 Scope 배열 */
            scopes: (Record<string, never> | boolean | string | number)[];
            /** @description API Key 식별자 */
            merchantApiKeyId: string;
            /** @description 식별·화면 표시용 Prefix */
            keyPrefix: string;
        };
        /** AcceptAccountInvitationRequest */
        AcceptAccountInvitationRequest: {
            /** @description 설정할 새 비밀번호 */
            newPassword: string;
            /** @description 발급 응답에서 받은 초대 Token 원문 */
            invitationToken: string;
        };
        /** ResendInvitationResponse */
        ResendInvitationResponse: {
            /** @description 새 초대의 만료 시각(UTC) */
            invitationExpiresAt: string;
            /** @description 대상 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 새 초대 Token 원문. 최초 1회만 노출된다. */
            invitationToken: string;
        };
        /** ChangeMerchantUserRoleResponse */
        ChangeMerchantUserRoleResponse: {
            /** @description 변경 후 역할 */
            role: string;
            /** @description 변경 시각(UTC) */
            changedAt: string;
            /** @description 대상 가맹점 사용자 식별자 */
            merchantUserId: string;
        };
        /** InviteMerchantSubAccountRequest */
        InviteMerchantSubAccountRequest: {
            /** @description ADMIN | VIEWER (OWNER 불가) */
            role: string;
            /** @description 가맹점 내에서 유일한 로그인 아이디 */
            loginId: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 가맹점 내에서 유일한 이메일 */
            email: string;
        };
        /** UpdateMerchantWebhookUrlRequest */
        UpdateMerchantWebhookUrlRequest: {
            /** @description http:// 또는 https:// 로 시작하는 수신 URL. null이나 빈 문자열이면 해제. */
            webhookUrl?: string | null;
        };
        "merchant-merchant-users-merchantUserId-reactivate-33084672": Record<string, never>;
        /** ListPaymentsResponse */
        ListPaymentsResponse: {
            /** @description 실제로 적용된 페이지 크기. 상한에 걸리면 요청값과 다르다. */
            size: number;
            /** @description 결제 배열(생성 시각 최신순) */
            payments: {
                /** @description 가맹점이 부여한 주문 식별자 */
                merchantOrderId: string;
                /** @description 결제 토큰 금액. Minor Unit 정수를 문자열로 준다. */
                paymentAmount: string;
                /** @description 온체인 거래 Hash. 고객이 제출하기 전이면 null. */
                transactionHash?: string | null;
                /** @description 블록체인 네트워크 코드 */
                network: string;
                /** @description 결제 자산 코드(USDC) */
                paymentAsset: string;
                /** @description 결제 생성 시각(UTC) */
                createdAt: string;
                /** @description KRW 주문 금액(원 단위 정수) */
                orderAmount: number;
                /** @description 토큰 소수 자릿수(USDC는 6) */
                tokenDecimals: number;
                /** @description 결제 식별자 */
                paymentId: string;
                /** @description 실패 사유. FAILED가 아니면 null. */
                failureReason?: string | null;
                /** @description 결제 완료 시각(UTC). SUCCEEDED가 아니면 null. */
                paidAt?: string | null;
                /** @description PaymentStatus 값 */
                status: string;
                /** @description 주문명 */
                orderName: string;
            }[];
            /** @description SUCCEEDED 결제의 주문 금액 합계(KRW). 정산 화면의 합계와 다르다 — 이쪽은 고객이 낸 금액이고, 정산 쪽은 수수료를 뺀 받을 금액이다. */
            succeededAmount: number;
            /** @description 그중 SUCCEEDED인 건수. totalCount와 함께 승인율의 재료다. */
            succeededCount: number;
            /** @description 조회한 페이지 번호(0부터) */
            page: number;
            /** @description 필터 전체에 걸린 건수(현재 페이지 건수가 아니다) */
            totalCount: number;
        };
        /** MerchantMeResponse */
        MerchantMeResponse: {
            /** @description OWNER | ADMIN | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 가맹점 식별자 */
            merchantId: string;
            /** @description 가맹점 사용자 식별자 */
            merchantUserId: string;
        };
        /** MerchantLoginResponse */
        MerchantLoginResponse: {
            /** @description OWNER | ADMIN | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 가맹점 식별자 */
            merchantId: string;
            /** @description 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 사용자 이름 */
            userName: string;
        };
        /** AcceptAccountInvitationResponse */
        AcceptAccountInvitationResponse: {
            /** @description 활성화된 계정의 로그인 아이디 */
            loginId: string;
            /** @description 활성화 시각(UTC) */
            activatedAt: string;
        };
        /** RevokeInvitationResponse */
        RevokeInvitationResponse: {
            /** @description 대상 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 취소 시각(UTC) */
            revokedAt: string;
        };
        /** ListMerchantUsersResponse */
        ListMerchantUsersResponse: {
            /** @description 가맹점 사용자 요약 배열(최신 생성순) */
            merchantUsers: {
                /** @description 생성(초대) 시각(UTC) */
                createdAt: string;
                /** @description 마지막 로그인 시각(UTC). 로그인한 적이 없으면 null. */
                lastLoginAt?: string | null;
                /** @description OWNER | ADMIN | VIEWER */
                role: string;
                /** @description 로그인 아이디 */
                loginId: string;
                /** @description 가맹점 사용자 식별자 */
                merchantUserId: string;
                /** @description 사용자 이름 */
                userName: string;
                /** @description 이메일 */
                email: string;
                /** @description 유효한(PENDING) 초대의 만료 시각(UTC). null이면 초대가 없거나 취소된 상태이고, 과거면 만료된 것이다 — INVITED 사용자가 왜 활성화되지 않았는지를 여기서 판단한다. */
                pendingInvitationExpiresAt?: string | null;
                /** @description INVITED | ACTIVE | LOCKED | SUSPENDED | TERMINATED */
                status: string;
            }[];
        };
        /** ChangeMerchantUserStatusResponse */
        ChangeMerchantUserStatusResponse: {
            /** @description 변경 시각(UTC) */
            changedAt: string;
            /** @description 대상 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 변경 후 계정 상태 */
            status: string;
        };
        /** ListMerchantApiKeysResponse */
        ListMerchantApiKeysResponse: {
            /** @description 발급된 API Key 요약 배열 */
            apiKeys: {
                /** @description 발급 시각(UTC) */
                createdAt: string;
                /** @description 발급 환경 */
                environment: string;
                /** @description 마지막 사용 시각(UTC). 사용 전에는 null. */
                lastUsedAt?: string | null;
                /** @description Key 이름 */
                keyName: string;
                /** @description 허용 Scope 배열 */
                scopes: (Record<string, never> | boolean | string | number)[];
                /** @description API Key 식별자 */
                merchantApiKeyId: string;
                /** @description 폐기 시각(UTC). ACTIVE면 null. */
                revokedAt?: string | null;
                /** @description 식별·화면 표시용 Prefix */
                keyPrefix: string;
                /** @description ACTIVE | REVOKED | EXPIRED */
                status: string;
            }[];
        };
        /** InviteMerchantSubAccountResponse */
        InviteMerchantSubAccountResponse: {
            /** @description 부여된 역할 */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 초대 만료 시각(UTC) */
            invitationExpiresAt: string;
            /** @description 생성된 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 초대 Token 원문. 최초 1회만 노출된다. */
            invitationToken: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 이메일 */
            email: string;
        };
        /** PaymentDetailResponse */
        PaymentDetailResponse: {
            /** @description Webhook 전송 이력(오래된 순). 설정하지 않았으면 빈 배열. */
            webhookDeliveries: {
                /** @description 생성 시각(UTC) */
                createdAt: string;
                /** @description 다음 재시도 시각 */
                nextRetryAt?: string | null;
                /** @description 마지막 응답 코드 */
                lastHttpStatus?: number | null;
                /** @description 마지막 오류 메시지 */
                lastErrorMessage?: string | null;
                /** @description 시도 횟수 */
                attemptCount: number;
                /** @description 전송 대상 URL */
                destinationUrl: string;
                /** @description 이벤트 종류 */
                eventType: string;
                /** @description 전송 식별자 */
                webhookDeliveryId: string;
                /** @description 전송 성공 시각(UTC) */
                deliveredAt?: string | null;
                /** @description WebhookDeliveryStatus 값 */
                status: string;
            }[];
            /** @description 견적 스냅샷. 언제나 있다. */
            quote: {
                /** @description 견적 시각(UTC) */
                quotedAt: string;
                /** @description 스프레드율 */
                spreadRate: number;
                /** @description 적용 환율 */
                appliedRate: number;
                /** @description 시장 환율 제공자 코드 */
                marketProviderCode: string;
                /** @description 시장 환율 */
                marketRate: number;
                /** @description 견적 만료 시각(UTC) */
                expiresAt: string;
            };
            /** @description 결제 본문. 언제나 있다. **가맹점 열은 없다**(언제나 자기 가맹점이다). */
            payment: {
                /** @description 주문 통화(KRW) */
                orderCurrency: string;
                /** @description PG 수취 지갑 주소 */
                receivingWallet: string;
                /** @description 가맹점이 부여한 주문 식별자 */
                merchantOrderId: string;
                /** @description 결제 토큰 금액. Minor Unit 정수를 문자열로 준다. */
                paymentAmount: string;
                /** @description 결제 만료 시각(UTC) */
                expiresAt: string;
                /** @description 블록체인 네트워크 코드 */
                network: string;
                /** @description 결제 자산 코드(USDC) */
                paymentAsset: string;
                /** @description 생성 시각(UTC) */
                createdAt: string;
                /** @description KRW 주문 금액(원 단위 정수) */
                orderAmount: number;
                /** @description 토큰 소수 자릿수 */
                tokenDecimals: number;
                /** @description 결제 식별자 */
                paymentId: string;
                /** @description 실패 사유. FAILED가 아니면 null. */
                failureReason?: string | null;
                /** @description 완료 시각(UTC). SUCCEEDED가 아니면 null. */
                paidAt?: string | null;
                /** @description 고객 지갑. 연결 전에는 null. */
                customerWallet?: string | null;
                /** @description PaymentStatus 값 */
                status: string;
                /** @description 주문명 */
                orderName: string;
            };
            /** @description 온체인 거래. Hash 제출 전에는 null. */
            blockchainTransaction?: {
                /** @description 실패 코드 */
                failureCode?: string | null;
                /** @description 확정에 필요한 Confirm 수 */
                requiredConfirmationCount: number;
                /** @description 실제 수령 금액(Minor Unit 문자열) */
                amountMinor?: string | null;
                /** @description 받은 주소 */
                toAddress?: string | null;
                /** @description 거래 Hash */
                transactionHash: string;
                /** @description 누적 Confirm 수 */
                confirmationCount: number;
                /** @description 토큰 Contract 주소 */
                tokenContractAddress?: string | null;
                /** @description 블록 번호 */
                blockNumber?: number | null;
                /** @description 감지 시각(UTC) */
                detectedAt?: string | null;
                /** @description 보낸 주소 */
                fromAddress?: string | null;
                /** @description 확정 시각(UTC) */
                confirmedAt?: string | null;
                /** @description 제출 시각(UTC) */
                submittedAt: string;
                /** @description BlockchainTransactionStatus 값 */
                status: string;
            };
            /** @description 환전 주문. 매도 전에는 null. */
            exchangeOrder?: {
                /** @description 거래소 수수료 */
                feeAmount?: number | null;
                /** @description 체결 완료 시각(UTC) */
                completedAt?: string | null;
                /** @description 거래소 코드(MVP는 FAKE) */
                providerCode: string;
                /** @description 평균 체결 환율 */
                averageExecutionRate?: number | null;
                /** @description 확보한 KRW */
                receivedAmount?: number | null;
                /** @description 체결 수량(Minor Unit 문자열) */
                executedAmount?: string | null;
                /** @description ExchangeOrderStatus 값 */
                status: string;
                /** @description 환전 주문 식별자 */
                exchangeOrderId: string;
            };
            /** @description 정산 채권. 환전 전에는 null. */
            settlementReceivable?: {
                /** @description 수수료 */
                feeAmount: number;
                /** @description 정산 예정 금액 */
                netAmount: number;
                /** @description 정산 예정일 */
                eligibleDate: string;
                /** @description 환전 손익. 음수 가능. */
                exchangeProfitLossAmount?: number | null;
                /** @description 정산 기준 금액 */
                grossAmount: number;
                /** @description 조정 금액(음수 가능) */
                adjustmentAmount: number;
                /** @description 적용 수수료율 */
                feeRate: number;
                /** @description 정산 채권 식별자 */
                settlementReceivableId: string;
                /** @description SettlementReceivableStatus 값 */
                status: string;
            };
            /** @description 체크아웃 세션. 언제나 있다. */
            checkoutSession: {
                /** @description 체크아웃 세션 식별자 */
                checkoutSessionId: string;
                /** @description 연결된 지갑. 연결 전에는 null. */
                connectedWallet?: string | null;
                /** @description 세션 만료 시각(UTC) */
                expiresAt: string;
                /** @description CheckoutSessionStatus 값 */
                status: string;
            };
        };
        /** IssueMerchantApiKeyRequest */
        IssueMerchantApiKeyRequest: {
            /** @description Key 이름(용도 식별용) */
            keyName: string;
            /** @description Scope 이름 배열. MVP는 PAYMENT_CREATE | PAYMENT_READ. */
            scopes: (Record<string, never> | boolean | string | number)[];
        };
        /** RevokeMerchantApiKeyResponse */
        RevokeMerchantApiKeyResponse: {
            /** @description 폐기된 API Key 식별자 */
            merchantApiKeyId: string;
            /** @description 폐기 시각(UTC) */
            revokedAt: string;
        };
        /** MerchantLoginRequest */
        MerchantLoginRequest: {
            /** @description 비밀번호 */
            password: string;
            /** @description 가맹점 식별 코드 */
            merchantCode: string;
            /** @description 가맹점 내 로그인 아이디 */
            loginId: string;
        };
        /** MerchantWebhookSettingsResponse */
        MerchantWebhookSettingsResponse: {
            /** @description 겹침 기간 동안만 값이 있는 **직전 비밀**. 그동안은 두 비밀 모두 통한다. 겹침이 끝나면 null. */
            previousSecret?: string | null;
            /** @description 서명 비밀의 세대. 교체할 때마다 1씩 증가한다. */
            secretVersion: number;
            /** @description 서명 비밀(`whsec_` 접두사). 이 값으로 X-PracticePay-Signature를 검증한다. */
            signingSecret: string;
            /** @description 직전 비밀이 무효가 되는 시각(UTC). previousSecret과 함께 있거나 함께 없다. */
            previousSecretValidUntil?: string | null;
            /** @description Webhook 수신 URL. 설정하지 않았으면 null. */
            webhookUrl?: string | null;
        };
        /** ChangeMerchantUserRoleRequest */
        ChangeMerchantUserRoleRequest: {
            /** @description 변경할 역할. ADMIN | VIEWER (OWNER 불가) */
            role: string;
        };
        /** ListSettlementReceivablesResponse */
        ListSettlementReceivablesResponse: {
            /** @description 실제로 적용된 페이지 크기 */
            size: number;
            /** @description 필터 전체의 정산 예정 금액 합계. **지급 경로에 살아 있는 것만**(PENDING/READY) 더한다 */
            totalNetAmount: number;
            /** @description 그중 보류(HELD)된 건수. 합계에서 빠진 몫이다 */
            heldCount: number;
            /** @description 조회한 페이지 번호(0부터) */
            page: number;
            /** @description 정산 채권 배열(정산 예정일 최신순) */
            settlementReceivables: {
                /** @description 정산 예정 금액 = gross - fee + adjustment */
                netAmount: number;
                /** @description 확보액과 정산 기준 금액의 차이. 음수 가능, READY 전에는 null. */
                exchangeProfitLossAmount?: number | null;
                /** @description 정산 기준 금액 */
                grossAmount: number;
                /** @description 가맹점이 부여한 주문 식별자 */
                merchantOrderId: string;
                /** @description 적용 수수료율 */
                feeRate: number;
                /** @description 생성 시각(UTC) */
                createdAt: string;
                /** @description 수수료 */
                feeAmount: number;
                /** @description 정산 통화(KRW) */
                settlementCurrency: string;
                /** @description 이 채권을 만든 결제 */
                paymentId: string;
                /** @description 정산 예정일(YYYY-MM-DD) */
                eligibleDate: string;
                /** @description 환전으로 확보한 KRW. READY 전에는 null. */
                exchangeReceivedAmount?: number | null;
                /** @description 조정 금액(음수 가능) */
                adjustmentAmount: number;
                /** @description 정산 채권 식별자 */
                settlementReceivableId: string;
                /** @description SettlementReceivableStatus 값(MVP 종착은 READY) */
                status: string;
            }[];
            /** @description 필터 전체에 걸린 건수 */
            totalCount: number;
            /** @description 보류된 금액 합계. 0이 아니면 화면이 눈에 띄게 그린다 */
            heldNetAmount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "merchant-list-api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMerchantApiKeysResponse"];
                };
            };
        };
    };
    "merchant-issue-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["IssueMerchantApiKeyRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueMerchantApiKeyResponse"];
                };
            };
        };
    };
    "merchant-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["MerchantLoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantLoginResponse"];
                };
            };
        };
    };
    "merchant-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "merchant-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantMeResponse"];
                };
            };
        };
    };
    "merchant-list-merchant-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMerchantUsersResponse"];
                };
            };
        };
    };
    "merchant-invite-sub-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["InviteMerchantSubAccountRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteMerchantSubAccountResponse"];
                };
            };
        };
    };
    "merchant-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPaymentsResponse"];
                };
            };
        };
    };
    "merchant-settlement-receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSettlementReceivablesResponse"];
                };
            };
        };
    };
    "merchant-get-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantWebhookSettingsResponse"];
                };
            };
        };
    };
    "merchant-update-webhook-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["UpdateMerchantWebhookUrlRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantWebhookSettingsResponse"];
                };
            };
        };
    };
    "merchant-accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["AcceptAccountInvitationRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptAccountInvitationResponse"];
                };
            };
        };
    };
    "merchant-revoke-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 폐기할 API Key 식별자 */
                merchantApiKeyId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeMerchantApiKeyResponse"];
                };
            };
        };
    };
    "merchant-payment-detail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDetailResponse"];
                };
            };
        };
    };
    "merchant-rotate-webhook-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantWebhookSettingsResponse"];
                };
            };
        };
    };
    "merchant-reactivate-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 대상 가맹점 사용자 식별자 */
                merchantUserId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeMerchantUserStatusResponse"];
                };
            };
        };
    };
    "merchant-change-user-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 대상 가맹점 사용자 식별자 */
                merchantUserId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ChangeMerchantUserRoleRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeMerchantUserRoleResponse"];
                };
            };
        };
    };
    "merchant-suspend-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 대상 가맹점 사용자 식별자 */
                merchantUserId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeMerchantUserStatusResponse"];
                };
            };
        };
    };
    "merchant-terminate-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 대상 가맹점 사용자 식별자 */
                merchantUserId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeMerchantUserStatusResponse"];
                };
            };
        };
    };
    "merchant-resend-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 대상 가맹점 사용자 식별자 */
                merchantUserId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendInvitationResponse"];
                };
            };
        };
    };
    "merchant-revoke-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 대상 가맹점 사용자 식별자 */
                merchantUserId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-merchant-users-merchantUserId-reactivate-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeInvitationResponse"];
                };
            };
        };
    };
}
