/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/merchant/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Key 목록 조회
         * @description OWNER/ADMIN만 조회할 수 있다. Secret 관련 필드(rawApiKey/secretHash)는 애초에 담기지 않는다.
         */
        get: operations["merchant-list-api-keys"];
        put?: never;
        /**
         * API Key 발급
         * @description OWNER/ADMIN만 발급할 수 있다. rawApiKey는 이 응답에서만 원문으로 보이고 DB에는 Hash만 남는다 — 다시 조회할 수 없으니 즉시 가맹점 서버에 전달해야 한다. environment는 받지 않는다(MVP는 항상 TEST).
         */
        post: operations["merchant-issue-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가맹점 콘솔 로그인
         * @description 로그인에 성공하면 세션 쿠키(Set-Cookie)를 내리고 본문에 신원 정보를 담는다. login_id는 가맹점 안에서만 유일해서 merchantCode로 어느 가맹점인지 먼저 밝힌다. 상태 변경 요청이라 CSRF 토큰(X-XSRF-TOKEN)이 필요하다 — GET /merchant/me로 먼저 XSRF-TOKEN 쿠키를 받는다.
         */
        post: operations["merchant-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 세션을 무효화한다. 본문이 없고 204를 돌려준다. 상태 변경 요청이라 CSRF 토큰이 필요하다.
         */
        post: operations["merchant-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 세션 사용자 조회(세션 복원)
         * @description 프론트가 새로고침 후 로그인 상태를 복원할 때 쓴다. 미인증이면 401을 돌려주고, 프론트는 그것을 '로그아웃 상태'로 해석한다. 이 GET은 CSRF 토큰 발급도 겸한다 — 응답에 XSRF-TOKEN 쿠키가 실린다.
         */
        get: operations["merchant-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/merchant/api-keys/{merchantApiKeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * API Key 폐기
         * @description OWNER/ADMIN만 폐기할 수 있다. 폐기된 Key는 다시 활성화하지 않는다 — 새 Key를 발급한다.
         */
        delete: operations["merchant-revoke-api-key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** IssueMerchantApiKeyResponse */
        IssueMerchantApiKeyResponse: {
            /** @description 발급 시각(UTC) */
            createdAt: string;
            /** @description 발급 환경. MVP는 TEST. */
            environment: string;
            /** @description Key 이름 */
            keyName: string;
            /** @description 전체 API Key 원문. 최초 1회만 노출된다. */
            rawApiKey: string;
            /** @description 허용 Scope 배열 */
            scopes: (Record<string, never> | boolean | string | number)[];
            /** @description API Key 식별자 */
            merchantApiKeyId: string;
            /** @description 식별·화면 표시용 Prefix */
            keyPrefix: string;
        };
        /** ListMerchantApiKeysResponse */
        ListMerchantApiKeysResponse: {
            /** @description 발급된 API Key 요약 배열 */
            apiKeys: {
                /** @description 발급 시각(UTC) */
                createdAt: string;
                /** @description 발급 환경 */
                environment: string;
                /** @description 마지막 사용 시각(UTC). 사용 전에는 null. */
                lastUsedAt?: string | null;
                /** @description Key 이름 */
                keyName: string;
                /** @description 허용 Scope 배열 */
                scopes: (Record<string, never> | boolean | string | number)[];
                /** @description API Key 식별자 */
                merchantApiKeyId: string;
                /** @description 폐기 시각(UTC). ACTIVE면 null. */
                revokedAt?: string | null;
                /** @description 식별·화면 표시용 Prefix */
                keyPrefix: string;
                /** @description ACTIVE | REVOKED | EXPIRED */
                status: string;
            }[];
        };
        "merchant-api-keys-merchantApiKeyId-33084672": Record<string, never>;
        /** MerchantMeResponse */
        MerchantMeResponse: {
            /** @description OWNER | ADMIN | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 가맹점 식별자 */
            merchantId: string;
            /** @description 가맹점 사용자 식별자 */
            merchantUserId: string;
        };
        /** MerchantLoginResponse */
        MerchantLoginResponse: {
            /** @description OWNER | ADMIN | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 가맹점 식별자 */
            merchantId: string;
            /** @description 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 사용자 이름 */
            userName: string;
        };
        /** IssueMerchantApiKeyRequest */
        IssueMerchantApiKeyRequest: {
            /** @description Key 이름(용도 식별용) */
            keyName: string;
            /** @description Scope 이름 배열. MVP는 PAYMENT_CREATE | PAYMENT_READ. */
            scopes: (Record<string, never> | boolean | string | number)[];
        };
        /** RevokeMerchantApiKeyResponse */
        RevokeMerchantApiKeyResponse: {
            /** @description 폐기된 API Key 식별자 */
            merchantApiKeyId: string;
            /** @description 폐기 시각(UTC) */
            revokedAt: string;
        };
        /** MerchantLoginRequest */
        MerchantLoginRequest: {
            /** @description 비밀번호 */
            password: string;
            /** @description 가맹점 식별 코드 */
            merchantCode: string;
            /** @description 가맹점 내 로그인 아이디 */
            loginId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "merchant-list-api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMerchantApiKeysResponse"];
                };
            };
        };
    };
    "merchant-issue-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["IssueMerchantApiKeyRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueMerchantApiKeyResponse"];
                };
            };
        };
    };
    "merchant-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["MerchantLoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantLoginResponse"];
                };
            };
        };
    };
    "merchant-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-api-keys-merchantApiKeyId-33084672"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "merchant-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantMeResponse"];
                };
            };
        };
    };
    "merchant-revoke-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 폐기할 API Key 식별자 */
                merchantApiKeyId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["merchant-api-keys-merchantApiKeyId-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeMerchantApiKeyResponse"];
                };
            };
        };
    };
}
