/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/internal-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내부 운영자 목록 조회
         * @description **SUPER_ADMIN만 조회할 수 있다** — 가맹점 목록(GET)이 VIEWER에게도 열려 있는 것과 다르다. 명부에는 직원 이메일·마지막 로그인·누가 SUPER_ADMIN인지가 담기고, 계정 관리 자체가 SUPER_ADMIN의 영역이기 때문이다. 비밀번호 해시는 담기지 않는다.
         */
        get: operations["admin-list-internal-users"];
        put?: never;
        /**
         * 내부 운영자 계정 발급
         * @description SUPER_ADMIN만 호출할 수 있다(일반 회원가입은 제공하지 않는다). invitationToken은 이 응답에서만 원문으로 보이며, **그 사람이 활성화할 곳은 이 콘솔 자신의 /accept-invitation**이다 — 가맹점 등록이 만드는 링크가 가맹점 콘솔을 가리키는 것과 대비된다.
         */
        post: operations["admin-issue-internal-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 내부 운영자 로그인
         * @description 로그인에 성공하면 세션 쿠키(Set-Cookie)를 내리고 본문에 신원 정보를 담는다. 가맹점 콘솔과 달리 merchantCode가 없다 — 내부 운영자는 특정 가맹점에 속하지 않는다. 상태 변경 요청이라 CSRF 토큰(X-XSRF-TOKEN)이 필요하다(GET /admin/me로 먼저 XSRF-TOKEN 쿠키를 받는다).
         */
        post: operations["admin-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로그인 감사 로그 조회
         * @description **SUPER_ADMIN만** 조회할 수 있다 — 실패 시도·클라이언트 IP·누가 로그인했는지가 담겨 내부 직원 명부와 같은 민감도다. 최근 시도를 최신순으로 돌려준다(성공·실패·잠금). 없는 로그인 아이디로의 시도는 internalUserId·userName이 null이고 attemptedLoginId만 남는다.
         */
        get: operations["admin-login-audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 세션을 무효화한다. 본문이 없고 204를 돌려준다. 상태 변경 요청이라 CSRF 토큰이 필요하다.
         */
        post: operations["admin-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 세션 사용자 조회(세션 복원)
         * @description 프론트가 새로고침 후 로그인 상태를 복원할 때 쓴다. 미인증이면 401이고 프론트는 그것을 '로그아웃 상태'로 해석한다. 이 GET은 CSRF 토큰 발급도 겸한다(응답에 XSRF-TOKEN 쿠키가 실린다).
         */
        get: operations["admin-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/merchant-login-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가맹점 로그인 감사 로그 조회
         * @description **SUPER_ADMIN/OPERATOR**가 조회할 수 있다 — 내부 직원 로그인 감사(SUPER_ADMIN 전용)와 달리 OPERATOR도 가맹점 업무를 맡아 포함한다. 전 가맹점의 로그인 시도(성공·실패·잠김)를 최신순으로 돌려준다. 기록은 api-merchant가 하고 조회는 이 콘솔이 한다. 없는 merchantCode 시도는 merchantId·merchantName이 null이고, 없는 loginId 시도는 userName이 null이다.
         */
        get: operations["admin-merchant-login-audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가맹점 목록 조회
         * @description 인증된 내부 운영자 전원이 조회할 수 있다 — VIEWER도 포함된다(VIEWER는 '조회 전용'으로 정의돼 있다). 등록(POST)만 SUPER_ADMIN/OPERATOR로 제한된다.
         */
        get: operations["admin-list-merchants"];
        put?: never;
        /**
         * 가맹점 등록(+ 최초 OWNER 초대)
         * @description SUPER_ADMIN/OPERATOR만 호출할 수 있다. 가맹점과 최초 OWNER 계정을 한 트랜잭션에서 만든다 — 가맹점은 스스로 가입할 수 없다. invitationToken은 이 응답에서만 원문으로 보이며, **그 OWNER가 활성화할 곳은 이 콘솔이 아니라 가맹점 콘솔의 /accept-invitation**이다.
         */
        post: operations["admin-register-merchant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 내역 조회(전 가맹점)
         * @description **인증된 내부 사용자 전원**(VIEWER 포함)이 조회할 수 있다. 쿼리 파라미터로 좁힌다: merchantId, status(PaymentStatus), from/to(생성 시각 ISO-8601 UTC), page(0부터), size. size는 서버가 최대 200으로 자르고, 실제로 적용된 값을 응답의 size로 돌려준다. 정렬은 생성 시각 최신순이다. paymentAmount는 Minor Unit 정수를 **문자열로** 준다 — 토큰 금액이 JavaScript Number의 안전 정수 범위를 넘을 수 있어서다.
         */
        get: operations["admin-payments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settlement-receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 정산 채권 조회(전 가맹점)
         * @description **인증된 내부 사용자 전원**(VIEWER 포함)이 조회할 수 있다. 쿼리 파라미터로 좁힌다: merchantId, status(SettlementReceivableStatus), eligibleFrom/eligibleTo(**정산 예정일 기준 날짜** YYYY-MM-DD — 결제 목록이 생성 시각을 쓰는 것과 다르다), page(0부터), size(최대 200). 정렬은 정산 예정일 최신순이다. **totalNetAmount는 현재 페이지가 아니라 필터 전체의 정산 예정 금액 합계**다 — 이 화면의 핵심 숫자라 목록과 함께 준다. 금액은 KRW 원 단위 정수라 모두 숫자로 준다(토큰 금액을 문자열로 주는 것과 다른 점).
         */
        get: operations["admin-settlement-receivables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/account-invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 수락(내부 운영자 계정 활성화)
         * @description 초대받은 내부 직원이 Token과 새 비밀번호로 계정을 INVITED → ACTIVE로 활성화한다. 인증이 필요 없고 **CSRF 토큰도 요구하지 않는다**(자격증명이 세션 쿠키가 아니라 본문의 Token 자체다). 가맹점 사용자 초대는 이 엔드포인트가 아니라 api-merchant의 같은 경로로 간다.
         */
        post: operations["admin-accept-invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 상세 조회
         * @description **인증된 내부 사용자 전원**(VIEWER 포함)이 조회할 수 있다. 결제 한 건의 전체 맥락을 단계별로 돌려준다: 견적·체크아웃 세션·온체인 거래·환전·정산 채권·Webhook 전송 이력. **흐름이 진행돼야 생기는 부분은 null이고, 그 null 자체가 "어디까지 갔는지"를 말해준다** (blockchainTransaction이 null이면 고객이 아직 Hash를 제출하지 않았다). 없는 결제는 404다. 토큰 금액(paymentAmount, blockchainTransaction.amountMinor, exchangeOrder.executedAmount)은 Minor Unit 정수를 **문자열로** 주고 KRW는 숫자로 준다.
         */
        get: operations["admin-payment-detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/internal-users/iu_002/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 내부 운영자 역할 변경
         * @description SUPER_ADMIN만 호출할 수 있다. role은 OPERATOR | VIEWER여야 한다 — **SUPER_ADMIN으로 승격하면 400이다**(초대와 같은 제약, 최초 SUPER_ADMIN은 Bootstrap으로만 만든다). 마지막 활성 SUPER_ADMIN을 강등하면 409다. 상태 변경 요청이라 CSRF 토큰이 필요하다.
         */
        post: operations["admin-change-internal-user-role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/internal-users/iu_002/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 내부 운영자 계정 상태 변경(정지·재개·종료)
         * @description SUPER_ADMIN만 호출할 수 있다. 마지막 경로 세그먼트로 동작을 고른다: suspend(ACTIVE→SUSPENDED) · reactivate(SUSPENDED→ACTIVE) · terminate(→TERMINATED, 되돌릴 수 없음). 자기 자신은 대상으로 삼을 수 없고(403), 마지막 활성 SUPER_ADMIN을 정지·종료하면 409다. 상태 변경 요청이라 CSRF 토큰이 필요하다.
         */
        post: operations["admin-change-internal-user-status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/merchants/mrc_001/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가맹점 사용자 명부 조회
         * @description 인증된 내부 운영자 전원이 조회할 수 있다 — VIEWER도 포함된다(GET /admin/merchants와 같은 스코핑). 관리 액션(POST)만 SUPER_ADMIN/OPERATOR로 제한된다. 비밀번호 해시는 담기지 않는다.
         */
        get: operations["admin-list-merchant-users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/webhook-deliveries/{webhookDeliveryId}/redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실패한 Webhook 전송 재전송
         * @description SUPER_ADMIN/OPERATOR만 실행할 수 있다. **보내는 것이 아니라 예약한다** — 전송과 OutboxEvent를 PENDING으로 되돌려 놓으면 기존 발행 Worker(10초 주기)가 평소 경로로 다시 보낸다. FAILED가 아닌 전송은 409, 없는 전송은 404.
         */
        post: operations["admin-redeliver-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/merchants/mrc_001/users/mu_001/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가맹점 사용자 역할 변경
         * @description SUPER_ADMIN/OPERATOR만 호출할 수 있다. role은 ADMIN | VIEWER여야 한다 — OWNER로 승격하면 400이다(도메인이 막는다). 마지막 활성 OWNER를 강등하면 409다. 상태 변경이라 CSRF 토큰이 필요하다.
         */
        post: operations["admin-change-merchant-user-role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/merchants/mrc_001/users/mu_001/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가맹점 사용자 상태 변경(정지·재개·종료)
         * @description SUPER_ADMIN/OPERATOR만 호출할 수 있다. 마지막 경로 세그먼트로 동작을 고른다: suspend · reactivate · terminate(되돌릴 수 없음). 대상이 경로의 가맹점 소속이 아니면 404. 마지막 활성 OWNER를 정지·종료하면 409다 — 이 API가 그 불변식이 실제로 트리거되는 첫 경로다. 상태 변경이라 CSRF 토큰이 필요하다.
         */
        post: operations["admin-change-merchant-user-status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptAccountInvitationRequest */
        AcceptAccountInvitationRequest: {
            /** @description 설정할 새 비밀번호 */
            newPassword: string;
            /** @description 발급 응답에서 받은 초대 Token 원문 */
            invitationToken: string;
        };
        /** AdminMeResponse */
        AdminMeResponse: {
            /** @description SUPER_ADMIN | OPERATOR | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /** @description SUPER_ADMIN | OPERATOR | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** ListInternalUsersResponse */
        ListInternalUsersResponse: {
            /** @description 내부 운영자 요약 배열(최신 생성순) */
            internalUsers: {
                /** @description 생성(초대) 시각(UTC) */
                createdAt: string;
                /** @description 마지막 로그인 시각(UTC). 로그인한 적이 없으면 null. */
                lastLoginAt?: string | null;
                /** @description SUPER_ADMIN | OPERATOR | VIEWER */
                role: string;
                /** @description 로그인 아이디 */
                loginId: string;
                /** @description 사용자 이름 */
                userName: string;
                /** @description 이메일 */
                email: string;
                /** @description 내부 운영자 식별자 */
                internalUserId: string;
                /** @description INVITED | ACTIVE | LOCKED | SUSPENDED | TERMINATED */
                status: string;
            }[];
        };
        "admin-webhook-deliveries-webhookDeliveryId-redeliver-33084672": Record<string, never>;
        /** ListLoginAuditResponse */
        ListLoginAuditResponse: {
            /** @description 로그인 감사 기록 배열(최신순) */
            entries: {
                /** @description 감사 기록 식별자 */
                auditId: string;
                /** @description 시도 시각(UTC) */
                occurredAt: string;
                /** @description 요청 원격 주소. 없으면 null. */
                clientIp?: string | null;
                /** @description 시도에 쓰인 로그인 아이디 */
                attemptedLoginId: string;
                /** @description 계정 이름. 없는 계정이면 null. */
                userName?: string | null;
                /** @description SUCCESS | INVALID_CREDENTIALS | LOCKED */
                outcome: string;
                /** @description 시도가 가리킨 계정 식별자. 없는 계정이면 null. */
                internalUserId?: string | null;
            }[];
        };
        /** AcceptAccountInvitationResponse */
        AcceptAccountInvitationResponse: {
            /** @description 활성화된 계정의 로그인 아이디 */
            loginId: string;
            /** @description 활성화 시각(UTC) */
            activatedAt: string;
        };
        /** PaymentDetailResponse */
        PaymentDetailResponse: {
            /** @description Webhook 전송 이력(오래된 순). 가맹점이 설정하지 않았으면 빈 배열. */
            webhookDeliveries: {
                /** @description 생성 시각(UTC) */
                createdAt: string;
                /** @description 다음 재시도 시각. RETRY_WAITING일 때만. */
                nextRetryAt?: string | null;
                /** @description 마지막 응답 코드. 네트워크 자체가 실패했으면 null. */
                lastHttpStatus?: number | null;
                /** @description 마지막 오류 메시지 */
                lastErrorMessage?: string | null;
                /** @description 시도 횟수 */
                attemptCount: number;
                /** @description 전송 대상 URL */
                destinationUrl: string;
                /** @description 이벤트 종류(payment.created 등) */
                eventType: string;
                /** @description 전송 식별자 */
                webhookDeliveryId: string;
                /** @description 전송 성공 시각(UTC) */
                deliveredAt?: string | null;
                /** @description WebhookDeliveryStatus 값 */
                status: string;
            }[];
            /** @description 견적 스냅샷. 결제 생성 트랜잭션에서 함께 만들어져 언제나 있다. */
            quote: {
                /** @description 견적 시각(UTC) */
                quotedAt: string;
                /** @description 스프레드율 */
                spreadRate: number;
                /** @description 적용 환율(시장 환율에 스프레드를 적용한 값) */
                appliedRate: number;
                /** @description 시장 환율 제공자 코드 */
                marketProviderCode: string;
                /** @description 시장 환율 */
                marketRate: number;
                /** @description 견적 만료 시각(UTC) */
                expiresAt: string;
            };
            /** @description 결제 본문. 언제나 있다. */
            payment: {
                /** @description 주문 통화(KRW) */
                orderCurrency: string;
                /** @description PG 수취 지갑 주소 */
                receivingWallet: string;
                /** @description 가맹점이 부여한 주문 식별자 */
                merchantOrderId: string;
                /** @description 결제 토큰 금액. Minor Unit 정수를 문자열로 준다. */
                paymentAmount: string;
                /** @description 결제 만료 시각(UTC) */
                expiresAt: string;
                /** @description 블록체인 네트워크 코드 */
                network: string;
                /** @description 가맹점 이름 */
                merchantName: string;
                /** @description 결제 자산 코드(USDC) */
                paymentAsset: string;
                /** @description 생성 시각(UTC) */
                createdAt: string;
                /** @description KRW 주문 금액(원 단위 정수) */
                orderAmount: number;
                /** @description 가맹점 식별자 */
                merchantId: string;
                /** @description 토큰 소수 자릿수 */
                tokenDecimals: number;
                /** @description 결제 식별자 */
                paymentId: string;
                /** @description 실패 사유. FAILED가 아니면 null. */
                failureReason?: string | null;
                /** @description 완료 시각(UTC). SUCCEEDED가 아니면 null. */
                paidAt?: string | null;
                /** @description 고객 지갑. 연결 전에는 null. */
                customerWallet?: string | null;
                /** @description PaymentStatus 값 */
                status: string;
                /** @description 주문명 */
                orderName: string;
            };
            /** @description 온체인 거래. 고객이 Hash를 제출하기 전에는 null. */
            blockchainTransaction?: {
                /** @description 실패 코드 */
                failureCode?: string | null;
                /** @description 확정에 필요한 Confirm 수 */
                requiredConfirmationCount: number;
                /** @description 실제 수령 금액(Minor Unit 문자열) */
                amountMinor?: string | null;
                /** @description 받은 주소 */
                toAddress?: string | null;
                /** @description 거래 Hash */
                transactionHash: string;
                /** @description 누적 Confirm 수 */
                confirmationCount: number;
                /** @description 토큰 Contract 주소 */
                tokenContractAddress?: string | null;
                /** @description 포함된 블록 번호. 감지 전에는 null. */
                blockNumber?: number | null;
                /** @description 감지 시각(UTC) */
                detectedAt?: string | null;
                /** @description 보낸 주소 */
                fromAddress?: string | null;
                /** @description 확정 시각(UTC) */
                confirmedAt?: string | null;
                /** @description 제출 시각(UTC) */
                submittedAt: string;
                /** @description BlockchainTransactionStatus 값 */
                status: string;
            };
            /** @description 환전 주문. 매도 전에는 null. */
            exchangeOrder?: {
                /** @description 거래소 수수료 */
                feeAmount?: number | null;
                /** @description 체결 완료 시각(UTC) */
                completedAt?: string | null;
                /** @description 거래소 코드(MVP는 FAKE) */
                providerCode: string;
                /** @description 평균 체결 환율 */
                averageExecutionRate?: number | null;
                /** @description 확보한 KRW */
                receivedAmount?: number | null;
                /** @description 체결 수량(Minor Unit 문자열) */
                executedAmount?: string | null;
                /** @description ExchangeOrderStatus 값 */
                status: string;
                /** @description 환전 주문 식별자 */
                exchangeOrderId: string;
            };
            /** @description 정산 채권. 환전 전에는 null. */
            settlementReceivable?: {
                /** @description 수수료 */
                feeAmount: number;
                /** @description 정산 예정 금액 */
                netAmount: number;
                /** @description 정산 예정일 */
                eligibleDate: string;
                /** @description 환전 손익(PG 마진). 음수 가능. */
                exchangeProfitLossAmount?: number | null;
                /** @description 정산 기준 금액 */
                grossAmount: number;
                /** @description 조정 금액(음수 가능) */
                adjustmentAmount: number;
                /** @description 적용 수수료율 */
                feeRate: number;
                /** @description 정산 채권 식별자 */
                settlementReceivableId: string;
                /** @description SettlementReceivableStatus 값 */
                status: string;
            };
            /** @description 체크아웃 세션. 결제 생성과 함께 만들어져 언제나 있다. */
            checkoutSession: {
                /** @description 체크아웃 세션 식별자 */
                checkoutSessionId: string;
                /** @description 연결된 지갑. 연결 전에는 null. */
                connectedWallet?: string | null;
                /** @description 세션 만료 시각(UTC) */
                expiresAt: string;
                /** @description CheckoutSessionStatus 값 */
                status: string;
            };
        };
        /** ChangeMerchantUserRoleResponse */
        ChangeMerchantUserRoleResponse: {
            /** @description 변경된 역할 */
            role: string;
            /** @description 변경 시각(UTC) */
            changedAt: string;
            /** @description 대상 가맹점 사용자 식별자 */
            merchantUserId: string;
        };
        /** RegisterMerchantResponse */
        RegisterMerchantResponse: {
            /** @description 가맹점 코드 */
            merchantCode: string;
            /** @description 생성된 가맹점 식별자 */
            merchantId: string;
            /** @description 초대 만료 시각(UTC) */
            invitationExpiresAt: string;
            /** @description 생성된 OWNER 계정 식별자 */
            ownerMerchantUserId: string;
            /** @description OWNER 로그인 아이디 */
            ownerLoginId: string;
            /** @description OWNER 초대 Token 원문. 최초 1회만 노출된다. */
            invitationToken: string;
            /** @description OWNER 이메일 */
            ownerEmail: string;
            /** @description 가맹점 이름 */
            merchantName: string;
        };
        /** IssueInternalUserResponse */
        IssueInternalUserResponse: {
            /** @description 부여된 역할 */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 초대 만료 시각(UTC) */
            invitationExpiresAt: string;
            /** @description 초대 Token 원문. 최초 1회만 노출된다. */
            invitationToken: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 이메일 */
            email: string;
            /** @description 생성된 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** ListMerchantLoginAuditResponse */
        ListMerchantLoginAuditResponse: {
            /** @description 가맹점 로그인 감사 기록 배열(최신순) */
            entries: {
                /** @description 감사 기록 식별자 */
                auditId: string;
                /** @description 시도 시각(UTC) */
                occurredAt: string;
                /** @description 시도가 가리킨 가맹점 식별자. 없는 가맹점이면 null. */
                merchantId?: string | null;
                /** @description 요청 원격 주소. 없으면 null. */
                clientIp?: string | null;
                /** @description 시도에 쓰인 로그인 아이디 */
                attemptedLoginId: string;
                /** @description 계정 이름. 없는 계정이면 null. */
                userName?: string | null;
                /** @description SUCCESS | INVALID_CREDENTIALS | LOCKED */
                outcome: string;
                /** @description 시도에 쓰인 가맹점 코드 */
                attemptedMerchantCode: string;
                /** @description 가맹점 이름. 없는 가맹점이면 null. */
                merchantName?: string | null;
            }[];
        };
        /** ChangeMerchantUserRoleRequest */
        ChangeMerchantUserRoleRequest: {
            /** @description 변경할 역할(ADMIN | VIEWER) */
            role: string;
        };
        /** RegisterMerchantRequest */
        RegisterMerchantRequest: {
            /** @description 가맹점 코드(전 시스템에서 유일, 가맹점 사용자 로그인에 쓰인다) */
            merchantCode: string;
            /** @description 최초 OWNER의 이름 */
            ownerUserName: string;
            /** @description 최초 OWNER의 로그인 아이디 */
            ownerLoginId: string;
            /** @description 결제 결과를 받을 Webhook URL. 선택값이다. */
            webhookUrl?: string | null;
            /** @description 최초 OWNER의 이메일 */
            ownerEmail: string;
            /** @description 가맹점 이름 */
            merchantName: string;
        };
        /** ChangeInternalUserStatusResponse */
        ChangeInternalUserStatusResponse: {
            /** @description 변경 시각(UTC) */
            changedAt: string;
            /** @description 대상 내부 운영자 식별자 */
            internalUserId: string;
            /** @description 변경된 상태(ACTIVE | SUSPENDED | TERMINATED) */
            status: string;
        };
        /** ListPaymentsResponse */
        ListPaymentsResponse: {
            /** @description 실제로 적용된 페이지 크기. 상한에 걸리면 요청값과 다르다. */
            size: number;
            /** @description 결제 배열(생성 시각 최신순) */
            payments: {
                /** @description 가맹점이 부여한 주문 식별자 */
                merchantOrderId: string;
                /** @description 결제 토큰 금액. Minor Unit 정수를 문자열로 준다. */
                paymentAmount: string;
                /** @description 온체인 거래 Hash. 고객이 제출하기 전이면 null. */
                transactionHash?: string | null;
                /** @description 블록체인 네트워크 코드 */
                network: string;
                /** @description 가맹점 이름 */
                merchantName: string;
                /** @description 결제 자산 코드(USDC) */
                paymentAsset: string;
                /** @description 결제 생성 시각(UTC) */
                createdAt: string;
                /** @description KRW 주문 금액(원 단위 정수) */
                orderAmount: number;
                /** @description 가맹점 식별자 */
                merchantId: string;
                /** @description 토큰 소수 자릿수(USDC는 6) */
                tokenDecimals: number;
                /** @description 결제 식별자 */
                paymentId: string;
                /** @description 실패 사유. FAILED가 아니면 null. */
                failureReason?: string | null;
                /** @description 결제 완료 시각(UTC). SUCCEEDED가 아니면 null. */
                paidAt?: string | null;
                /** @description PaymentStatus 값 */
                status: string;
                /** @description 주문명 */
                orderName: string;
            }[];
            /** @description SUCCEEDED 결제의 주문 금액 합계(KRW). **성공한 것만 더한다** — 전체를 더하면 만료·실패한 결제까지 매출처럼 보인다. */
            succeededAmount: number;
            /** @description 그중 SUCCEEDED인 건수. totalCount와 함께 승인율의 재료다. */
            succeededCount: number;
            /** @description 조회한 페이지 번호(0부터) */
            page: number;
            /** @description 필터 전체에 걸린 건수(현재 페이지 건수가 아니다) */
            totalCount: number;
        };
        /** ListSettlementReceivablesResponse */
        ListSettlementReceivablesResponse: {
            /** @description 실제로 적용된 페이지 크기 */
            size: number;
            /** @description 필터 전체의 정산 예정 금액 합계 */
            totalNetAmount: number;
            /** @description 조회한 페이지 번호(0부터) */
            page: number;
            /** @description 정산 채권 배열(정산 예정일 최신순) */
            settlementReceivables: {
                /** @description 정산 예정 금액 = gross - fee + adjustment */
                netAmount: number;
                /** @description 확보액과 정산 기준 금액의 차이(PG 마진). 음수 가능, READY 전에는 null. */
                exchangeProfitLossAmount?: number | null;
                /** @description 정산 기준 금액 */
                grossAmount: number;
                /** @description 가맹점이 부여한 주문 식별자 */
                merchantOrderId: string;
                /** @description 적용 수수료율 */
                feeRate: number;
                /** @description 가맹점 이름 */
                merchantName: string;
                /** @description 생성 시각(UTC) */
                createdAt: string;
                /** @description 수수료 */
                feeAmount: number;
                /** @description 정산 통화(KRW) */
                settlementCurrency: string;
                /** @description 가맹점 식별자 */
                merchantId: string;
                /** @description 이 채권을 만든 결제 */
                paymentId: string;
                /** @description 정산 예정일(YYYY-MM-DD) */
                eligibleDate: string;
                /** @description 환전으로 확보한 KRW. READY 전에는 null. */
                exchangeReceivedAmount?: number | null;
                /** @description 조정 금액(음수 가능) */
                adjustmentAmount: number;
                /** @description 정산 채권 식별자 */
                settlementReceivableId: string;
                /** @description SettlementReceivableStatus 값(MVP 종착은 READY) */
                status: string;
            }[];
            /** @description 필터 전체에 걸린 건수 */
            totalCount: number;
        };
        /** ChangeInternalUserRoleResponse */
        ChangeInternalUserRoleResponse: {
            /** @description 변경된 역할 */
            role: string;
            /** @description 변경 시각(UTC) */
            changedAt: string;
            /** @description 대상 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** IssueInternalUserRequest */
        IssueInternalUserRequest: {
            /** @description OPERATOR | VIEWER. **SUPER_ADMIN을 보내면 400이다** — 최초 SUPER_ADMIN은 Bootstrap으로만 생성한다. */
            role: string;
            /** @description 전 시스템에서 유일한 로그인 아이디 */
            loginId: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 전 시스템에서 유일한 이메일 */
            email: string;
        };
        /** RedeliverWebhookResponse */
        RedeliverWebhookResponse: {
            /** @description 누적 시도 횟수. 재전송은 이 값을 초기화하지 않는다(재시도 예산을 새로 주지 않는다). */
            attemptCount: number;
            /** @description 되돌린 전송 식별자 */
            webhookDeliveryId: string;
            /** @description 되돌린 뒤의 상태(PENDING). **아직 보내지 않았다는 뜻**이라 '성공'으로 읽으면 안 된다. */
            status: string;
        };
        /** AdminListMerchantUsersResponse */
        AdminListMerchantUsersResponse: {
            /** @description 가맹점 사용자 요약 배열(최신 생성순) */
            merchantUsers: {
                /** @description 생성(초대) 시각(UTC) */
                createdAt: string;
                /** @description 마지막 로그인 시각(UTC). 없으면 null. */
                lastLoginAt?: string | null;
                /** @description OWNER | ADMIN | VIEWER */
                role: string;
                /** @description 로그인 아이디 */
                loginId: string;
                /** @description 가맹점 사용자 식별자 */
                merchantUserId: string;
                /** @description 사용자 이름 */
                userName: string;
                /** @description 이메일 */
                email: string;
                /** @description 유효한 초대의 만료 시각(UTC). 없으면 null. */
                pendingInvitationExpiresAt?: string | null;
                /** @description INVITED | ACTIVE | LOCKED | SUSPENDED | TERMINATED */
                status: string;
            }[];
        };
        /** ChangeMerchantUserStatusResponse */
        ChangeMerchantUserStatusResponse: {
            /** @description 변경 시각(UTC) */
            changedAt: string;
            /** @description 대상 가맹점 사용자 식별자 */
            merchantUserId: string;
            /** @description 변경된 상태(ACTIVE | SUSPENDED | TERMINATED) */
            status: string;
        };
        /** ChangeInternalUserRoleRequest */
        ChangeInternalUserRoleRequest: {
            /** @description 변경할 역할(OPERATOR | VIEWER) */
            role: string;
        };
        /** ListMerchantsResponse */
        ListMerchantsResponse: {
            /** @description 가맹점 요약 배열 */
            merchants: {
                /** @description 등록 시각(UTC) */
                createdAt: string;
                /** @description 가맹점 코드(로그인 시 사용) */
                merchantCode: string;
                /** @description 가맹점 식별자 */
                merchantId: string;
                /** @description 가맹점 상태 */
                status: string;
                /** @description 가맹점 이름 */
                merchantName: string;
            }[];
        };
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** @description 비밀번호 */
            password: string;
            /** @description 내부 운영자 로그인 아이디 */
            loginId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admin-list-internal-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInternalUsersResponse"];
                };
            };
        };
    };
    "admin-issue-internal-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["IssueInternalUserRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueInternalUserResponse"];
                };
            };
        };
    };
    "admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
        };
    };
    "admin-login-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLoginAuditResponse"];
                };
            };
        };
    };
    "admin-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["admin-webhook-deliveries-webhookDeliveryId-redeliver-33084672"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "admin-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeResponse"];
                };
            };
        };
    };
    "admin-merchant-login-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMerchantLoginAuditResponse"];
                };
            };
        };
    };
    "admin-list-merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMerchantsResponse"];
                };
            };
        };
    };
    "admin-register-merchant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["RegisterMerchantRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterMerchantResponse"];
                };
            };
        };
    };
    "admin-payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPaymentsResponse"];
                };
            };
        };
    };
    "admin-settlement-receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSettlementReceivablesResponse"];
                };
            };
        };
    };
    "admin-accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["AcceptAccountInvitationRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptAccountInvitationResponse"];
                };
            };
        };
    };
    "admin-payment-detail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDetailResponse"];
                };
            };
        };
    };
    "admin-change-internal-user-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ChangeInternalUserRoleRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInternalUserRoleResponse"];
                };
            };
        };
    };
    "admin-change-internal-user-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["admin-webhook-deliveries-webhookDeliveryId-redeliver-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInternalUserStatusResponse"];
                };
            };
        };
    };
    "admin-list-merchant-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminListMerchantUsersResponse"];
                };
            };
        };
    };
    "admin-redeliver-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 재전송할 Webhook 전송 식별자 */
                webhookDeliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["admin-webhook-deliveries-webhookDeliveryId-redeliver-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeliverWebhookResponse"];
                };
            };
        };
    };
    "admin-change-merchant-user-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ChangeMerchantUserRoleRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeMerchantUserRoleResponse"];
                };
            };
        };
    };
    "admin-change-merchant-user-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["admin-webhook-deliveries-webhookDeliveryId-redeliver-33084672"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeMerchantUserStatusResponse"];
                };
            };
        };
    };
}
