/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/internal-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내부 운영자 목록 조회
         * @description **SUPER_ADMIN만 조회할 수 있다** — 가맹점 목록(GET)이 VIEWER에게도 열려 있는 것과 다르다. 명부에는 직원 이메일·마지막 로그인·누가 SUPER_ADMIN인지가 담기고, 계정 관리 자체가 SUPER_ADMIN의 영역이기 때문이다. 비밀번호 해시는 담기지 않는다.
         */
        get: operations["admin-list-internal-users"];
        put?: never;
        /**
         * 내부 운영자 계정 발급
         * @description SUPER_ADMIN만 호출할 수 있다(일반 회원가입은 제공하지 않는다). invitationToken은 이 응답에서만 원문으로 보이며, **그 사람이 활성화할 곳은 이 콘솔 자신의 /accept-invitation**이다 — 가맹점 등록이 만드는 링크가 가맹점 콘솔을 가리키는 것과 대비된다.
         */
        post: operations["admin-issue-internal-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 내부 운영자 로그인
         * @description 로그인에 성공하면 세션 쿠키(Set-Cookie)를 내리고 본문에 신원 정보를 담는다. 가맹점 콘솔과 달리 merchantCode가 없다 — 내부 운영자는 특정 가맹점에 속하지 않는다. 상태 변경 요청이라 CSRF 토큰(X-XSRF-TOKEN)이 필요하다(GET /admin/me로 먼저 XSRF-TOKEN 쿠키를 받는다).
         */
        post: operations["admin-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 세션을 무효화한다. 본문이 없고 204를 돌려준다. 상태 변경 요청이라 CSRF 토큰이 필요하다.
         */
        post: operations["admin-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 세션 사용자 조회(세션 복원)
         * @description 프론트가 새로고침 후 로그인 상태를 복원할 때 쓴다. 미인증이면 401이고 프론트는 그것을 '로그아웃 상태'로 해석한다. 이 GET은 CSRF 토큰 발급도 겸한다(응답에 XSRF-TOKEN 쿠키가 실린다).
         */
        get: operations["admin-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가맹점 목록 조회
         * @description 인증된 내부 운영자 전원이 조회할 수 있다 — VIEWER도 포함된다(VIEWER는 '조회 전용'으로 정의돼 있다). 등록(POST)만 SUPER_ADMIN/OPERATOR로 제한된다.
         */
        get: operations["admin-list-merchants"];
        put?: never;
        /**
         * 가맹점 등록(+ 최초 OWNER 초대)
         * @description SUPER_ADMIN/OPERATOR만 호출할 수 있다. 가맹점과 최초 OWNER 계정을 한 트랜잭션에서 만든다 — 가맹점은 스스로 가입할 수 없다. invitationToken은 이 응답에서만 원문으로 보이며, **그 OWNER가 활성화할 곳은 이 콘솔이 아니라 가맹점 콘솔의 /accept-invitation**이다.
         */
        post: operations["admin-register-merchant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/account-invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 초대 수락(내부 운영자 계정 활성화)
         * @description 초대받은 내부 직원이 Token과 새 비밀번호로 계정을 INVITED → ACTIVE로 활성화한다. 인증이 필요 없고 **CSRF 토큰도 요구하지 않는다**(자격증명이 세션 쿠키가 아니라 본문의 Token 자체다). 가맹점 사용자 초대는 이 엔드포인트가 아니라 api-merchant의 같은 경로로 간다.
         */
        post: operations["admin-accept-invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** IssueInternalUserResponse */
        IssueInternalUserResponse: {
            /** @description 부여된 역할 */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 초대 만료 시각(UTC) */
            invitationExpiresAt: string;
            /** @description 초대 Token 원문. 최초 1회만 노출된다. */
            invitationToken: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 이메일 */
            email: string;
            /** @description 생성된 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** AcceptAccountInvitationRequest */
        AcceptAccountInvitationRequest: {
            /** @description 설정할 새 비밀번호 */
            newPassword: string;
            /** @description 발급 응답에서 받은 초대 Token 원문 */
            invitationToken: string;
        };
        /** AdminMeResponse */
        AdminMeResponse: {
            /** @description SUPER_ADMIN | OPERATOR | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /** @description SUPER_ADMIN | OPERATOR | VIEWER */
            role: string;
            /** @description 로그인 아이디 */
            loginId: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 내부 운영자 식별자 */
            internalUserId: string;
        };
        /** ListMerchantsResponse */
        ListMerchantsResponse: {
            /** @description 가맹점 요약 배열 */
            merchants: {
                /** @description 등록 시각(UTC) */
                createdAt: string;
                /** @description 가맹점 코드(로그인 시 사용) */
                merchantCode: string;
                /** @description 가맹점 식별자 */
                merchantId: string;
                /** @description 가맹점 상태 */
                status: string;
                /** @description 가맹점 이름 */
                merchantName: string;
            }[];
        };
        /** ListInternalUsersResponse */
        ListInternalUsersResponse: {
            /** @description 내부 운영자 요약 배열(최신 생성순) */
            internalUsers: {
                /** @description 생성(초대) 시각(UTC) */
                createdAt: string;
                /** @description 마지막 로그인 시각(UTC). 로그인한 적이 없으면 null. */
                lastLoginAt?: string | null;
                /** @description SUPER_ADMIN | OPERATOR | VIEWER */
                role: string;
                /** @description 로그인 아이디 */
                loginId: string;
                /** @description 사용자 이름 */
                userName: string;
                /** @description 이메일 */
                email: string;
                /** @description 내부 운영자 식별자 */
                internalUserId: string;
                /** @description INVITED | ACTIVE | LOCKED | SUSPENDED | TERMINATED */
                status: string;
            }[];
        };
        /** RegisterMerchantRequest */
        RegisterMerchantRequest: {
            /** @description 가맹점 코드(전 시스템에서 유일, 가맹점 사용자 로그인에 쓰인다) */
            merchantCode: string;
            /** @description 최초 OWNER의 이름 */
            ownerUserName: string;
            /** @description 최초 OWNER의 로그인 아이디 */
            ownerLoginId: string;
            /** @description 결제 결과를 받을 Webhook URL. 선택값이다. */
            webhookUrl?: string | null;
            /** @description 최초 OWNER의 이메일 */
            ownerEmail: string;
            /** @description 가맹점 이름 */
            merchantName: string;
        };
        "admin-logout-33084672": Record<string, never>;
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** @description 비밀번호 */
            password: string;
            /** @description 내부 운영자 로그인 아이디 */
            loginId: string;
        };
        /** IssueInternalUserRequest */
        IssueInternalUserRequest: {
            /** @description OPERATOR | VIEWER (최초 SUPER_ADMIN은 Bootstrap으로만 생성) */
            role: string;
            /** @description 전 시스템에서 유일한 로그인 아이디 */
            loginId: string;
            /** @description 사용자 이름 */
            userName: string;
            /** @description 전 시스템에서 유일한 이메일 */
            email: string;
        };
        /** AcceptAccountInvitationResponse */
        AcceptAccountInvitationResponse: {
            /** @description 활성화된 계정의 로그인 아이디 */
            loginId: string;
            /** @description 활성화 시각(UTC) */
            activatedAt: string;
        };
        /** RegisterMerchantResponse */
        RegisterMerchantResponse: {
            /** @description 가맹점 코드 */
            merchantCode: string;
            /** @description 생성된 가맹점 식별자 */
            merchantId: string;
            /** @description 초대 만료 시각(UTC) */
            invitationExpiresAt: string;
            /** @description 생성된 OWNER 계정 식별자 */
            ownerMerchantUserId: string;
            /** @description OWNER 로그인 아이디 */
            ownerLoginId: string;
            /** @description OWNER 초대 Token 원문. 최초 1회만 노출된다. */
            invitationToken: string;
            /** @description OWNER 이메일 */
            ownerEmail: string;
            /** @description 가맹점 이름 */
            merchantName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admin-list-internal-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInternalUsersResponse"];
                };
            };
        };
    };
    "admin-issue-internal-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["IssueInternalUserRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueInternalUserResponse"];
                };
            };
        };
    };
    "admin-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
        };
    };
    "admin-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["admin-logout-33084672"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "admin-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMeResponse"];
                };
            };
        };
    };
    "admin-list-merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMerchantsResponse"];
                };
            };
        };
    };
    "admin-register-merchant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["RegisterMerchantRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterMerchantResponse"];
                };
            };
        };
    };
    "admin-accept-invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["AcceptAccountInvitationRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptAccountInvitationResponse"];
                };
            };
        };
    };
}
