/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checkout/sessions/{checkoutSessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 체크아웃 화면 렌더용 조회
         * @description 체크아웃 페이지를 그리는 데 필요한 모든 정보를 한 번에 준다. 인증이 없다 — checkoutSessionId를 아는 것 자체가 권한이다. 만료·취소·완료된 세션도 그대로 돌려주므로 프론트는 status로 화면을 나눈다.
         */
        get: operations["checkout-get-session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions/{checkoutSessionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 취소
         * @description 고객이 결제를 포기한다. 요청 본문이 없다. PAYMENT_SUBMITTED 이후에는 온체인 전송을 되돌릴 수 없어 409로 거부된다.
         */
        post: operations["checkout-cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions/{checkoutSessionId}/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 구매자 정보 입력
         * @description 고객이 이름·이메일·휴대전화를 직접 입력한다. 지갑 연결보다 앞선 단계다 — 서명 이후에 입력을 요구하면 돈은 나갔는데 결제가 미완인 창이 생긴다. 다시 호출하면 덮어쓰고, 결제 전송을 제출한 뒤에는 409다.
         */
        post: operations["checkout-submit-customer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions/{checkoutSessionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 상태 폴링(경량)
         * @description Confirm 대기 구간에서 3초 간격으로 호출한다. 전체 조회와 나눈 이유는 폴링이 10회 이상 반복되는데 주문·견적 정보를 매번 다시 보낼 이유가 없어서다. 최대 5분 뒤에는 폴링을 멈추고 새로고침을 안내한다.
         */
        get: operations["checkout-get-status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions/{checkoutSessionId}/transaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 전송한 Transaction Hash 제출
         * @description 고객 지갑이 USDC 전송을 브로드캐스트한 뒤 그 Hash를 제출한다. 성공 응답은 '결제가 됐다'가 아니라 '제출을 접수했다'는 뜻이다 — 확정은 배치 Worker가 하므로 프론트는 곧바로 상태 폴링으로 넘어간다.
         */
        post: operations["checkout-submit-transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/sessions/{checkoutSessionId}/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 지갑 연결
         * @description 고객이 지갑을 연결한 시점을 기록한다. 지갑 재연결은 지원하지 않는다 — 이미 연결된 뒤 다시 호출하면 409다.
         */
        post: operations["checkout-connect-wallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConnectWalletRequest */
        ConnectWalletRequest: {
            /** @description 고객이 연결한 EVM 지갑 주소(0x + 40 hex) */
            walletAddress: string;
        };
        /** CancelCheckoutSessionResponse */
        CancelCheckoutSessionResponse: {
            /** @description 돌아갈 가맹점 URL(cancelUrl). 가맹점이 지정하지 않았으면 null. */
            redirectUrl?: string | null;
            /** @description 체크아웃 세션 식별자 */
            checkoutSessionId: string;
            /** @description 취소에 성공하면 CANCELLED */
            checkoutSessionStatus: string;
        };
        /** SubmitCustomerResponse */
        SubmitCustomerResponse: {
            /** @description 마스킹된 휴대전화 번호 */
            phoneMasked: string;
            /** @description 마스킹된 이름. 응답에는 원본이 실리지 않는다 */
            nameMasked: string;
            /** @description 체크아웃 세션 식별자 */
            checkoutSessionId: string;
            /** @description 마스킹된 이메일 */
            emailMasked: string;
            /** @description CREATED였다면 이 호출로 OPEN이 된다 */
            checkoutSessionStatus: string;
        };
        /** SubmitTransactionResponse */
        SubmitTransactionResponse: {
            /** @description 결제 식별자 */
            paymentId: string;
            /** @description 체크아웃 세션 식별자 */
            checkoutSessionId: string;
            /** @description 제출에 성공하면 PAYMENT_SUBMITTED. 이후 고객 취소가 불가능해진다. */
            checkoutSessionStatus: string;
            /** @description 제출에 성공하면 PROCESSING */
            paymentStatus: string;
            /** @description PG가 추적하는 온체인 거래 식별자 */
            blockchainTransactionId: string;
        };
        /** CheckoutStatusResponse */
        CheckoutStatusResponse: {
            /** @description 결제가 SUCCEEDED가 됐을 때만 채워지는 이동 대상(successUrl). 프론트는 리다이렉트 시점을 스스로 추론하지 말고 이 필드가 채워지는 것을 신호로 삼는다. */
            redirectUrl?: string | null;
            /** @description 확정에 필요한 Confirmation 수 */
            requiredConfirmationCount: number;
            /** @description 현재 Confirmation 수. 아직 제출 전이면 0. */
            confirmationCount: number;
            /** @description 실패 사유 코드. FAILED일 때만 채워진다. 고객에게 그대로 노출하지 말고 안내 문구로 번역한다. */
            failureReason?: string | null;
            /** @description 체크아웃 세션 상태 */
            checkoutSessionStatus: string;
            /** @description 제출된 Transaction Hash. 제출 전에는 null. */
            transactionHash?: string | null;
            /** @description 결제 상태. SUCCEEDED가 되면 결제가 확정된 것이다. */
            paymentStatus: string;
        };
        /** SubmitTransactionRequest */
        SubmitTransactionRequest: {
            /** @description 브로드캐스트된 전송의 Transaction Hash */
            transactionHash: string;
        };
        /** SubmitCustomerRequest */
        SubmitCustomerRequest: {
            /** @description 국내 휴대전화 번호(01X-XXXX-XXXX, 하이픈은 있어도 없어도 된다) */
            phone: string;
            /** @description 구매자 이름(100자 이내) */
            name: string;
            /** @description 구매자 이메일. 결제에 문제가 생겼을 때의 주 연락 수단이다 */
            email: string;
        };
        /** ConnectWalletResponse */
        ConnectWalletResponse: {
            /** @description 체크아웃 세션 식별자 */
            checkoutSessionId: string;
            /** @description 연결에 성공하면 WALLET_CONNECTED */
            checkoutSessionStatus: string;
            /** @description 연결된 지갑 주소 */
            connectedWallet: string;
        };
        /** CheckoutSessionResponse */
        CheckoutSessionResponse: {
            /** @description 취소 시 돌아갈 가맹점 URL. 가맹점이 지정하지 않았으면 null. */
            cancelUrl?: string | null;
            /** @description 적용된 환율 견적 */
            quote: {
                /** @description 환율 산정 시각(UTC) */
                quotedAt: string;
                /** @description 적용 환율(KRW/USDC). 문자열로 준다 — 부동소수점 변환으로 정밀도를 잃지 않기 위해서다. */
                appliedRate: string;
                /** @description 견적 만료 시각(UTC) */
                expiresAt: string;
            };
            /** @description 체크아웃 세션 식별자 */
            checkoutSessionId: string;
            /** @description 결제 성공 후 고객을 보낼 가맹점 URL */
            successUrl: string;
            /** @description 이 주문에 대응하는 결제·전송 정보 */
            payment: {
                /** @description 전송할 토큰 금액(Minor Unit). 문자열이다 — JavaScript Number의 안전 정수 범위를 넘을 수 있어서 숫자로 다루면 정밀도를 잃는다. BigInt나 문자열로 처리한다. */
                amount: string;
                /** @description 결제 확정에 필요한 Confirmation 수 */
                requiredConfirmationCount: number;
                /** @description EVM Chain ID. 상수로 박지 말고 이 응답에서 받아 쓴다. */
                chainId: number;
                /** @description 토큰 소수 자릿수. USDC는 6. */
                tokenDecimals: number;
                /** @description 결제 식별자 */
                paymentId: string;
                /** @description USDC Contract 주소. 토큰을 Symbol로 판단하지 않고 (네트워크, Contract) 조합으로 다룬다. */
                tokenContractAddress: string;
                /** @description 이 금액을 보낼 수취 지갑 주소 */
                receivingWallet: string;
                /** @description 결제 자산. MVP는 USDC. */
                asset: string;
                /** @description CREATED | READY | PROCESSING | CONFIRMING | SUCCEEDED | EXPIRED | FAILED */
                paymentStatus: string;
                /** @description 전송할 블록체인 네트워크 */
                network: string;
            };
            /** @description CREATED | OPEN | WALLET_CONNECTED | PAYMENT_SUBMITTED | COMPLETED | EXPIRED | CANCELLED */
            checkoutSessionStatus: string;
            /** @description 연결된 고객 지갑 주소. 연결 전에는 null. */
            connectedWallet?: string | null;
            /** @description 세션 만료 시각(UTC). 지나면 변경 요청이 410으로 거부된다. */
            expiresAt: string;
            /** @description 가맹점 주문 정보 */
            order: {
                /** @description 주문 금액(KRW, 원 단위 정수) */
                orderAmount: number;
                /** @description 주문 통화. MVP는 항상 KRW. */
                orderCurrency: string;
                /** @description 가맹점이 정한 주문 이름 */
                orderName: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "checkout-get-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 체크아웃 세션 식별자. 결제 생성 응답의 checkoutSessionId를 그대로 쓴다. */
                checkoutSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
        };
    };
    "checkout-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 체크아웃 세션 식별자. 결제 생성 응답의 checkoutSessionId를 그대로 쓴다. */
                checkoutSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelCheckoutSessionResponse"];
                };
            };
        };
    };
    "checkout-submit-customer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 체크아웃 세션 식별자. 결제 생성 응답의 checkoutSessionId를 그대로 쓴다. */
                checkoutSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["SubmitCustomerRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitCustomerResponse"];
                };
            };
        };
    };
    "checkout-get-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 체크아웃 세션 식별자. 결제 생성 응답의 checkoutSessionId를 그대로 쓴다. */
                checkoutSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutStatusResponse"];
                };
            };
        };
    };
    "checkout-submit-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 체크아웃 세션 식별자. 결제 생성 응답의 checkoutSessionId를 그대로 쓴다. */
                checkoutSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["SubmitTransactionRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitTransactionResponse"];
                };
            };
        };
    };
    "checkout-connect-wallet": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 체크아웃 세션 식별자. 결제 생성 응답의 checkoutSessionId를 그대로 쓴다. */
                checkoutSessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ConnectWalletRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectWalletResponse"];
                };
            };
        };
    };
}
